### ISSUE TITLE
Watermark after temp licence install

### ISSUE THREAD

**Issue by npglambert** [jupiter-jazz/atomkraft-nuke#1]
I've finally got a temp licence from the web site tonight, but after installing I still get the watermark.
I'm on Mac OSX 10.7.5, running Nuke 7.0.6 with AtomKraft 1.2.1
The utility seems to work, loading the file & running the server.
The firewall is aware of, and not blocking the server.

Anything you can suggest I try?

Thanks,
Nick

**Comment by specialed** [comment]
Nick,

I had the same issue until I modified the .ini file.

### AtomKraft Configuration File

[AtomKraft]

### License server

### Uncomment the line below once you have a license server running on

### the computer.

### It may be necessary to replace 'localhost' with the output of

### 'licutils hostname'. On most setups, it is possible to skip this

### configuration entirely.

license_server=[insert your server name here]

Then in the AtomRender under the option tab there is a a place to enter the server name.. this will get rid of the watermark for the script in question.

So far I've had to enter the server name once per script but it's a start.

Hope this helps,

Eduardo

**Comment by npglambert** [comment]
Cheers Eduardo,
That has worked a treat. Thanks for taking the time to reply.

Nick
