### ISSUE TITLE
Nuke 9?

### ISSUE THREAD

**Issue by sebastianelsner** [jupiter-jazz/atomkraft-nuke#11]
Hey,

any plans on availability?

Cheers

Sebastian

**Comment by pberto** [comment]
No plans yet.

**Comment by sebastianelsner** [comment]
ok, thanks.
Btw. your seems support@jupiter-jazz.... is broken. My mail provider is complaining about a missing AAAAA record.

**Comment by WACOMalt** [comment]
Really wanting this update as well. main thing I'm missing in Nuke 9. I cant use 8 in my pipeline so I cant use atomkraft. Or I'd be buying it right now.
