### ISSUE TITLE
Crash Bug

### ISSUE THREAD

**Issue by guiramalho** [jupiter-jazz/atomkraft-nuke#3]
Hi all,

I use atomkraft since beta and I really love it, but is very common to nuke quit itself during render, there is no error message, nuke renders 3 or 4 frames and than quits... I reopen nuke render more 3 or 4 frames and it quits again... Is there any clue of what is going on ?

Best
Guilherme R.

**Comment by guiramalho** [comment]
Hi all,

Just found out that turnnig off image baking solves my problem !!!
Cheers !!!

:-)
Gui R.

**Comment by SamoHomsak** [comment]
Hi.
I have the same problem. Could you explain a bit more in details what you did to solve this crashing? Where did you turn off image baking? Was it AtomRender/Options/Baking/image-off? I have it off (default setting) - but I have on AtomTexture...
Best,
Samo

**Comment by SamoHomsak** [comment]
It surely has something to do with baking settings. If I turned off AtomTexture baking Nuke crashes almost immediately. So I came to a stage where I've turned on both (image and atomTexture) - but to "on in Nuke command line session". And it lasted the longest. Which is not really a solution but at least improvement of the bug in my case.

**Comment by SamoHomsak** [comment]
It also helps if you render only one write at a time

**Comment by guiramalho** [comment]
Hi Samo.
Actually I had the same results, just after I wrote that post Nuke crashed again, it is just crashing less...
I'm running it on an Hackintosh, it has 4 actual cores and 8 with hyper-treading, so I decided to use only 4 threads in AtomRender/Options/threads.
With the backing off and the threads set to 4 I had the best results, It went rendering all nite. Still is not 100% but crashes much less.
Best
Gui

**Comment by SamoHomsak** [comment]
Thanx. Will try with less cores
Best,
Samo

**Comment by pberto** [comment]
Please try the new version:

https://atomkraft.hk/nuke

**Comment by guiramalho** [comment]
HI Paolo,

I spoke with some render-farm providers like ZYNC, etc. To convince them to support Atomkraft, do you now any Atomkraft renderfarm in the cloud ?

Best

Gui R.

**Comment by pberto** [comment]
Several months ago we discussed with Zync and IIRC the conditions were not
so interesting, maybe now things have changed.

P

On Fri, Jan 31, 2014 at 1:12 AM, guiramalho notifications@github.comwrote:

> HI Paolo,
> 
> I spoke with some render-farm providers like ZYNC, etc. To convince them
> to support Atomkraft, do you now any Atomkraft renderfarm in the cloud ?
> 
> Best
> 
> Gui R.
> 
> On Jan 29, 2014, at 3:33 AM, Paolo Berto notifications@github.com
> wrote:
> 
> > Closed #3.
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jupiter-jazz/atomkraft-nuke/issues/3#issuecomment-33702794
> .

## 

paolo berto durante
j cube inc. tokyo, japan
http://j-cube.jp
