### ISSUE TITLE
Watermark after install on Nuke 8

### ISSUE THREAD

**Issue by npglambert** [jupiter-jazz/atomkraft-nuke#6]
I'm running on Mac OS 10.8.5 & even though the licence server is running & seen in the nodes panel I get the watermarked output...
![screen shot 2014-01-29 at 19 24 47](https://f.cloud.github.com/assets/4268094/2041437/2657f756-89c5-11e3-8eb7-37c5c1a78209.png)

**Comment by specialed** [comment]
Typing the server name into the field left of the license server info tab should get rid of the watermark.

**Comment by npglambert** [comment]
Unfortunately not :(
Running from the terminal I get this:

oading /Library/Application Support/Nuke/8.0/plugins/AtomKraft/plugin/AtomRender.dylib
[AtomKraft] Loading /Library/Application Support/Nuke/8.0/plugins/AtomKraft/atomkraft.ini
3DL SEVERE ERROR L2033: invalid license key

# [atomkraft:timing]: setup          : 0.000605 s

# [atomkraft:timing]: camera & lights: 0.001678 s

# [atomkraft:timing]: displays       : 0.000151 s

# [atomkraft:timing]: looks          : 3e-06 s

# [atomkraft:timing]: geometry bounds: 3.8e-05 s

[AtomRender] SERVER ERROR L2033: invalid license key

# [atomkraft:timing]: geometry       : 3.56285 s

# [atomkraft:timing]: total          : 3.56546 s

**Comment by specialed** [comment]
had the same issue until I modified the .ini file.
AtomKraft Configuration File

[AtomKraft]
License server
Uncomment the line below once you have a license server running on
the computer.
It may be necessary to replace 'localhost' with the output of
'licutils hostname'. On most setups, it is possible to skip this
configuration entirely.

license_server=[insert your server name here]

Then in the AtomRender under the option tab there is a a place to enter the server name.. this will get rid of the watermark for the script in question.

**Comment by npglambert** [comment]
I'd already tried that, I think the error in the terminal might be the cause. Not sure why it says invalid licence key when the server is happy with it. Strange.

![atomkraft_nuke8_mac](https://f.cloud.github.com/assets/4268094/2055138/a9406a08-8ac0-11e3-9206-c3c743fb903f.jpg)

**Comment by specialed** [comment]
Did you try using the IP address of the server instead of the name?

**Comment by npglambert** [comment]
Still no luck, I don't think it has anything to to with this as the terminal is saying the key is invalid:

Loading /Library/Application Support/Nuke/8.0/plugins/AtomKraft/plugin/AtomRender.dylib
[AtomKraft] Loading /Library/Application Support/Nuke/8.0/plugins/AtomKraft/atomkraft.ini
3DL SEVERE ERROR L2033: invalid license key

# [atomkraft:timing]: setup          : 0.000548 s

# [atomkraft:timing]: camera & lights: 0.001751 s

# [atomkraft:timing]: displays       : 0.000151 s

# [atomkraft:timing]: looks          : 3e-06 s

# [atomkraft:timing]: geometry bounds: 3.9e-05 s

[AtomRender] SERVER ERROR L2033: invalid license key

# [atomkraft:timing]: geometry       : 3.38669 s

# [atomkraft:timing]: total          : 3.3893 s

# [atomkraft:timing]: setup          : 0.000413 s

# [atomkraft:timing]: camera & lights: 0.001444 s

# [atomkraft:timing]: displays       : 7.9e-05 s

# [atomkraft:timing]: looks          : 4e-06 s

# [atomkraft:timing]: geometry bounds: 1.8e-05 s

[AtomRender] SERVER ERROR L2033: invalid license key

# [atomkraft:timing]: geometry       : 3.56964 s

# [atomkraft:timing]: total          : 3.57173 s

**Comment by pberto** [comment]
The key is obviously invalid, you are trying to run AK 1.3 with a 1.2 license. You need to get an updated license.

**Comment by npglambert** [comment]
New Issue Opened as my licence is still valid, it's dated to April 28th 2014, if you'd bothered to look at the images I attached. I'm very upset by this flippant closure of a very serious problem.

**Comment by npglambert** [comment]
I've tried regenerating & still get the Watermark:
![screen shot 2014-02-04 at 11 50 02](https://f.cloud.github.com/assets/4268094/2075681/ac71a0c8-8d92-11e3-8949-84a79fef8a9d.png)

**Comment by pberto** [comment]
The license you posted was for JJAKN12. Since you are contacting us by mail too let's follow up there, don;t worry, we can generate manually a license for you if the website could not update yours. You are perfectly entitled to have a license for AK1.3, let us just see /why/ you cannot re-generate a 1.3 license from your account.

**Comment by npglambert** [comment]
Thank you,
  I have to leave the office now for 4 days so will not be able
to check anything out until the weekend. I had to rent a Renderman
licence to get the last job completed. So you can see why I am upset.

**Comment by npglambert** [comment]
Not 100% sure, but after trying the regenerated licence with the following in the
ini file seems to have worked: license_server=localhost

Before, either the ip address or local machine name or leaving blank would work,
but this seems to be the final piece of the puzzle. I'll test more when I get back at the
weekend.

**Comment by virtualritz** [comment]
You need a 1.3 license to run AK 1.3. You are using a 1.2 license.
