### ISSUE TITLE
Project3D not working as expected

### ISSUE THREAD

**Issue by npglambert** [jupiter-jazz/atomkraft-nuke#8]
I've uploaded a video showing the issue here:
https://dl.dropboxusercontent.com/u/1305031/AtomKraft_Project3D.mov

Both Nukes scanline & Renderman output as expected, but AtomKraft 1.3.1
seems to loose the plot with projections.

**Comment by npglambert** [comment]
Any updates?

**Comment by bratgot** [comment]
AK uses object UV's for textures- Project3D doesn't appear to remap UVs

You should be able to simply pipe your texture into the modelbuilder and use a UVProject node to remap the ModelBuilder's UV to the camera projection. Append a Normals node to the ModelBuidler, set to action to build to create the needed Normals.

Hope that helps.

**Comment by npglambert** [comment]
Thanks Marty, I'm away on location 'till Monday, so will give that a try then :)

**Comment by npglambert** [comment]
Nope, still no dice.

**Comment by pberto** [comment]
Foundry changed the class of Project3D with basically no notice in the api, you will need a new build. We plan to ship 1.3.2 soon.

**Comment by npglambert** [comment]
Many thanks

**Comment by bratgot** [comment]
Fwiw, until 1.3.2 ships; 

Not sure why not.  Check screenshot. 

![screen shot 2014-02-21 at 5 42 55 am](https://f.cloud.github.com/assets/6686638/2220482/36d9e88e-9a4e-11e3-880e-8aadcafe84ed.png)

**Comment by npglambert** [comment]
Thanks again Marty, still no dice here. I've posted another video showing what I'm getting:
https://dl.dropboxusercontent.com/u/1305031/AtomKraft_UV_Prob.mov

**Comment by bratgot** [comment]
hmmm - that does look weird: Here that script

set cut_paste_input [stack 0]
version 8.0 v3
BackdropNode {
 inputs 0
 name BackdropNode2
 tile_color 0xaaaaaa00
 label "UV PROJECT"
 note_font_size 12
 selected true
 xpos -285
 ypos -454
 bdwidth 110
 bdheight 428
}
BackdropNode {
 inputs 0
 name BackdropNode1
 tile_color 0xaaaaaa00
 label "Project3d\n"
 note_font_size 19
 selected true
 xpos -540
 ypos -454
 bdwidth 140
 bdheight 476
}
Camera2 {
 inputs 0
 translate {1.338142395 0.6471083164 1.338142633}
 rotate {-18.87800083 44.99999442 0}
 focal 14.4
 name Camera2
 selected true
 xpos -460
 ypos 136
}
push $cut_paste_input
Camera2 {
 translate {0.4497350752 0.9902502298 1.67843461}
 rotate {-29.67800181 14.999997 0}
 name Camera1
 label PROJECTOR
 selected true
 xpos -519
 ypos -374
}
set Ne1748c0 [stack 0]
ColorBars {
 inputs 0
 name ColorBars1
 selected true
 xpos -275
 ypos -374
}
set Ne19e590 [stack 0]
Project3D2 {
 inputs 2
 crop false
 name Project3D1
 selected true
 xpos -530
 ypos -193
}
ModelBuilder {
 shape 3
 mode 3
 scene "
version 2
scenegraph {
  name 'Root'
  visible 1
  transform 1.000000000e+00 0.000000000e+00 0.000000000e+00 0.000000000e+00 0.000000000e+00 1.000000000e+00 0.000000000e+00 0.000000000e+00 0.000000000e+00 0.000000000e+00 1.000000000e+00 0.000000000e+00 0.000000000e+00 0.000000000e+00 0.000000000e+00 1.000000000e+00
  geometry 0
  children 1 [
    scenegraph {
      name 'Cube1'
      visible 1
      transform 6.110319495e-01 0.000000000e+00 0.000000000e+00 0.000000000e+00 0.000000000e+00 6.110319495e-01 0.000000000e+00 0.000000000e+00 0.000000000e+00 0.000000000e+00 6.110319495e-01 0.000000000e+00 3.609716892e-02 0.000000000e+00 4.859006405e-02 1.000000000e+00
      geometry {
        vertices 8 8 0 10 1 14 0 18 0 9 0 11 0 15 0 19 0
        edges 24 1 9 10 2 0 0 3 7 1 0 2 11 14 3 1 1 5 1 1 1 3 15 18 4 1 2 7 3 1 1 0 19 8 5 0 3 1 5 1 0 4 6 22 5 0 0 12 0 2 0 5 0 12 2 1 1 16 2 3 1 4 10 9 2 1 5 23 17 0 1 6 2 16 3 1 2 20 4 4 1 5 14 11 3 1 6 13 21 0 1 7 4 20 4 1 3 22 6 5 1 6 18 15 4 1 7 17 23 0 1 7 8 19 5 0 4 21 13 0 0
        faces 6 13 0 1 0 9 0 11 0 15 0 19 0
        vertex_attrs 1 [
          attribute {
            name 'pts_3d'
            type 'vec3'
            startTime 0.00000000000000000e+00
            initialVals 8 [
              + -5.000000000e-01 -5.000000000e-01 -5.000000000e-01
              + 5.000000000e-01 -5.000000000e-01 -5.000000000e-01
              + 5.000000000e-01 5.000000000e-01 -5.000000000e-01
              + -5.000000000e-01 5.000000000e-01 -5.000000000e-01
              + -5.000000000e-01 -5.000000000e-01 5.000000000e-01
              + 5.000000000e-01 -5.000000000e-01 5.000000000e-01
              + 5.000000000e-01 5.000000000e-01 5.000000000e-01
              + -5.000000000e-01 5.000000000e-01 5.000000000e-01
            ]
            keys 0 [
            ]
          }
        ]
        edge_attrs 2 [
          attribute {
            name 'seam'
            type 'bool'
            startTime 0.00000000000000000e+00
            initialVals 24 [
              -
              -
              + 1
              + 1
              + 1
              + 1
              -
              -
              -
              -
              + 1
              + 1
              + 1
              + 1
              + 1
              + 1
              + 1
              + 1
              + 1
              + 1
              + 1
              + 1
              -
              -
            ]
            keys 0 [
            ]
          }
          attribute {
            name 'uv'
            type 'vec4'
            startTime 0.00000000000000000e+00
            initialVals 24 [
              + 2.424588352e-01 3.105629683e-01 0.000000000e+00 1.000000000e+00
              + 4.123379588e-01 1.412852854e-01 0.000000000e+00 1.000000000e+00
              + 6.196289062e-01 3.084929287e-01 0.000000000e+00 1.000000000e+00
              + 1.412531137e-01 5.141378380e-03 0.000000000e+00 1.000000000e+00
              + 6.196289062e-01 6.176189184e-01 0.000000000e+00 1.000000000e+00
              + 5.109193735e-03 2.762262523e-01 0.000000000e+00 1.000000000e+00
              + 5.109193735e-03 2.762262523e-01 0.000000000e+00 1.000000000e+00
              + 2.424588352e-01 3.105629683e-01 0.000000000e+00 1.000000000e+00
              + 2.424588352e-01 3.105629683e-01 0.000000000e+00 1.000000000e+00
              + 3.436645567e-01 6.159844995e-01 0.000000000e+00 1.000000000e+00
              + 4.123379588e-01 1.412852854e-01 0.000000000e+00 1.000000000e+00
              + 9.229804277e-01 3.084929287e-01 0.000000000e+00 1.000000000e+00
              + 6.153509021e-01 4.129716158e-01 0.000000000e+00 1.000000000e+00
              + 3.436645567e-01 6.159844995e-01 0.000000000e+00 1.000000000e+00
              + 6.196289062e-01 5.141378380e-03 0.000000000e+00 1.000000000e+00
              + 9.229804277e-01 6.176189184e-01 0.000000000e+00 1.000000000e+00
              + 9.229804277e-01 5.141378380e-03 0.000000000e+00 1.000000000e+00
              + 3.430630565e-01 9.551414251e-01 0.000000000e+00 1.000000000e+00
              + 6.196289062e-01 3.142673373e-01 0.000000000e+00 1.000000000e+00
              + 4.507723730e-03 6.153830886e-01 0.000000000e+00 1.000000000e+00
              + 9.229804277e-01 3.142673373e-01 0.000000000e+00 1.000000000e+00
              + 3.906254191e-03 9.545398951e-01 0.000000000e+00 1.000000000e+00
              + 3.436645567e-01 6.159844995e-01 0.000000000e+00 1.000000000e+00
              + 4.507723730e-03 6.153830886e-01 0.000000000e+00 1.000000000e+00
            ]
            keys 0 [
            ]
          }
        ]
        face_attrs 0 [
        ]
        selected 0
      }
      children 0 [
      ]
    }
  ]
}
"
 name ModelBuilder2
 selected true
 xpos -530
 ypos -82
}
TransformGeo {
 translate {0.8650000095 0 0}
 name TransformGeo1
 tile_color 0xdbc1cc00
 label "offset\n"
 selected true
 xpos -530
 ypos -38
}
push $Ne1748c0
push $Ne19e590
ModelBuilder {
 shape 3
 mode 3
 scene "
version 2
scenegraph {
  name 'Root'
  visible 1
  transform 1.000000000e+00 0.000000000e+00 0.000000000e+00 0.000000000e+00 0.000000000e+00 1.000000000e+00 0.000000000e+00 0.000000000e+00 0.000000000e+00 0.000000000e+00 1.000000000e+00 0.000000000e+00 0.000000000e+00 0.000000000e+00 0.000000000e+00 1.000000000e+00
  geometry 0
  children 1 [
    scenegraph {
      name 'Cube1'
      visible 1
      transform 6.110319495e-01 0.000000000e+00 0.000000000e+00 0.000000000e+00 0.000000000e+00 6.110319495e-01 0.000000000e+00 0.000000000e+00 0.000000000e+00 0.000000000e+00 6.110319495e-01 0.000000000e+00 3.609716892e-02 0.000000000e+00 4.859006405e-02 1.000000000e+00
      geometry {
        vertices 8 8 0 10 1 14 0 18 0 9 0 11 0 15 0 19 0
        edges 24 1 9 10 2 0 0 3 7 1 0 2 11 14 3 1 1 5 1 1 1 3 15 18 4 1 2 7 3 1 1 0 19 8 5 0 3 1 5 1 0 4 6 22 5 0 0 12 0 2 0 5 0 12 2 1 1 16 2 3 1 4 10 9 2 1 5 23 17 0 1 6 2 16 3 1 2 20 4 4 1 5 14 11 3 1 6 13 21 0 1 7 4 20 4 1 3 22 6 5 1 6 18 15 4 1 7 17 23 0 1 7 8 19 5 0 4 21 13 0 0
        faces 6 13 0 1 0 9 0 11 0 15 0 19 0
        vertex_attrs 1 [
          attribute {
            name 'pts_3d'
            type 'vec3'
            startTime 0.00000000000000000e+00
            initialVals 8 [
              + -5.000000000e-01 -5.000000000e-01 -5.000000000e-01
              + 5.000000000e-01 -5.000000000e-01 -5.000000000e-01
              + 5.000000000e-01 5.000000000e-01 -5.000000000e-01
              + -5.000000000e-01 5.000000000e-01 -5.000000000e-01
              + -5.000000000e-01 -5.000000000e-01 5.000000000e-01
              + 5.000000000e-01 -5.000000000e-01 5.000000000e-01
              + 5.000000000e-01 5.000000000e-01 5.000000000e-01
              + -5.000000000e-01 5.000000000e-01 5.000000000e-01
            ]
            keys 0 [
            ]
          }
        ]
        edge_attrs 2 [
          attribute {
            name 'seam'
            type 'bool'
            startTime 0.00000000000000000e+00
            initialVals 24 [
              -
              -
              + 1
              + 1
              + 1
              + 1
              -
              -
              -
              -
              + 1
              + 1
              + 1
              + 1
              + 1
              + 1
              + 1
              + 1
              + 1
              + 1
              + 1
              + 1
              -
              -
            ]
            keys 0 [
            ]
          }
          attribute {
            name 'uv'
            type 'vec4'
            startTime 0.00000000000000000e+00
            initialVals 24 [
              + 2.424588352e-01 3.105629683e-01 0.000000000e+00 1.000000000e+00
              + 4.123379588e-01 1.412852854e-01 0.000000000e+00 1.000000000e+00
              + 6.196289062e-01 3.084929287e-01 0.000000000e+00 1.000000000e+00
              + 1.412531137e-01 5.141378380e-03 0.000000000e+00 1.000000000e+00
              + 6.196289062e-01 6.176189184e-01 0.000000000e+00 1.000000000e+00
              + 5.109193735e-03 2.762262523e-01 0.000000000e+00 1.000000000e+00
              + 5.109193735e-03 2.762262523e-01 0.000000000e+00 1.000000000e+00
              + 2.424588352e-01 3.105629683e-01 0.000000000e+00 1.000000000e+00
              + 2.424588352e-01 3.105629683e-01 0.000000000e+00 1.000000000e+00
              + 3.436645567e-01 6.159844995e-01 0.000000000e+00 1.000000000e+00
              + 4.123379588e-01 1.412852854e-01 0.000000000e+00 1.000000000e+00
              + 9.229804277e-01 3.084929287e-01 0.000000000e+00 1.000000000e+00
              + 6.153509021e-01 4.129716158e-01 0.000000000e+00 1.000000000e+00
              + 3.436645567e-01 6.159844995e-01 0.000000000e+00 1.000000000e+00
              + 6.196289062e-01 5.141378380e-03 0.000000000e+00 1.000000000e+00
              + 9.229804277e-01 6.176189184e-01 0.000000000e+00 1.000000000e+00
              + 9.229804277e-01 5.141378380e-03 0.000000000e+00 1.000000000e+00
              + 3.430630565e-01 9.551414251e-01 0.000000000e+00 1.000000000e+00
              + 6.196289062e-01 3.142673373e-01 0.000000000e+00 1.000000000e+00
              + 4.507723730e-03 6.153830886e-01 0.000000000e+00 1.000000000e+00
              + 9.229804277e-01 3.142673373e-01 0.000000000e+00 1.000000000e+00
              + 3.906254191e-03 9.545398951e-01 0.000000000e+00 1.000000000e+00
              + 3.436645567e-01 6.159844995e-01 0.000000000e+00 1.000000000e+00
              + 4.507723730e-03 6.153830886e-01 0.000000000e+00 1.000000000e+00
            ]
            keys 0 [
            ]
          }
        ]
        face_attrs 0 [
        ]
        selected 0
      }
      children 0 [
      ]
    }
  ]
}
"
 name ModelBuilder1
 selected true
 xpos -275
 ypos -134
}
Normals {
 action build
 name Normals1
 selected true
 xpos -275
 ypos -93
}
UVProject {
 inputs 2
 name UVProject1
 selected true
 xpos -275
 ypos -23
}
Scene {
 inputs 2
 name Scene1
 selected true
 xpos -264
 ypos 8
}
push 0
AtomRender {
 inputs 3
 primary_visibility REYES
 render_direction "bottom to top"
 anti_aliasing_samples 10
 auto_pixel_samples false
 shading_samples 0.1
 volume_shading_rate 0
 pixel_filter_expansion 0
 pixel_filter_sharpness 0
 proxy_degradation 0.1
 proxy_degradation_mode "interactive only"
 inkline_style none
 outline_width 1
 outline_color 0
 feature_line_width 1
 interior_line_color 0
 inkline_width_unit pixel
 render_motion_blur true
 ray_trace_motion false
 motion_blur "transformation & deformation"
 geometry_motion_segments 1
 camera_motion_segments 1
 extreme_blur_sampling 0
 shutter 0.5
 shutteroffset start
 shuttercustomoffset 0.5
 global_illumination_samples 0.2
 shadow_samples 4
 area_light_samples 16
 ray_depth 3
 specular_depth 2
 diffuse_depth 1
 ray_bias 0.1
 nuke_transparency true
 metric_scale_factor 1
 image_baking off
 atomtexture_baking on
 show_progress false
 threads 0
 texture_memory 0
 name AtomRender1
 selected true
 xpos -300
 ypos 162
}
Viewer {
 frame 1
 input_process false
 name Viewer2
 selected true
 xpos -75
 ypos 159
}

**Comment by bratgot** [comment]
if you can, post you model builder node - I'll take a look

**Comment by npglambert** [comment]
Script is here, but no image sequence I'm afraid:
https://dl.dropboxusercontent.com/u/1305031/playing_nuk308_c01_v03_AtomKraft_131.nk.zip

**Comment by bratgot** [comment]
Thanks Nick! I'll check it out.

**Comment by bratgot** [comment]
After playing with the file and more testing - we eagerly await v1.3.2 ;)

**Comment by npglambert** [comment]
Thanks for thanking the time to check it out Marty,
It's a real strange one isn't it.

**Comment by pberto** [comment]
Fixed in 1.3.2

**Comment by pberto** [comment]
Released: https://atomkraft.hk/nuke/full

Closing.
